# Generated by Django 5.2.8 on 2025-11-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nuevo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código Nuevo')),
                ('codigo_antiguo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Antiguo')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autor', models.CharField(max_length=300, verbose_name='Autor')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ubicacion_seccion', models.CharField(max_length=50, verbose_name='Ubicación - Sección')),
                ('ubicacion_repisa', models.CharField(max_length=50, verbose_name='Ubicación - Repisa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Activo Bibliográfico',
                'verbose_name_plural': 'Activos Bibliográficos',
                'ordering': ['codigo_nuevo'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('activobibliografico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.activobibliografico')),
                ('materia', models.CharField(max_length=200, verbose_name='Materia')),
                ('editorial', models.CharField(max_length=200, verbose_name='Editorial')),
                ('edicion', models.CharField(max_length=100, verbose_name='Edición')),
                ('codigo_seccion_full', models.CharField(max_length=100, verbose_name='Código Completo de Sección')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
            bases=('inventario.activobibliografico',),
        ),
        migrations.CreateModel(
            name='TrabajoGrado',
            fields=[
                ('activobibliografico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.activobibliografico')),
                ('modalidad', models.CharField(choices=[('TESIS', 'Tesis'), ('PROYECTO DE GRADO', 'Proyecto de Grado'), ('TRABAJO DIRIGIDO', 'Trabajo Dirigido')], max_length=30, verbose_name='Modalidad')),
                ('tutor', models.CharField(max_length=300, verbose_name='Tutor')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('facultad', models.CharField(max_length=200, verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Trabajo de Grado',
                'verbose_name_plural': 'Trabajos de Grado',
            },
            bases=('inventario.activobibliografico',),
        ),
    ]
