# Generated by Django 5.2.8 on 2025-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobibliografico',
            name='codigo_nuevo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código Nuevo'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='codigo_nuevo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código Nuevo'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='codigo_nuevo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código Nuevo'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='codigo_nuevo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código Nuevo'),
        ),
    ]
