# Generated by Django 5.2.8 on 2025-11-18 20:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActivoBibliografico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_nuevo', models.CharField(db_index=True, max_length=50, verbose_name='Código Nuevo')),
                ('codigo_antiguo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Antiguo')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autor', models.CharField(max_length=300, verbose_name='Autor')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ubicacion_seccion', models.CharField(max_length=50, verbose_name='Ubicación - Sección')),
                ('ubicacion_repisa', models.CharField(max_length=50, verbose_name='Ubicación - Repisa')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Activo Bibliográfico',
                'verbose_name_plural': 'historical Activos Bibliográficos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLibro',
            fields=[
                ('activobibliografico_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='inventario.activobibliografico')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_nuevo', models.CharField(db_index=True, max_length=50, verbose_name='Código Nuevo')),
                ('codigo_antiguo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Antiguo')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autor', models.CharField(max_length=300, verbose_name='Autor')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ubicacion_seccion', models.CharField(max_length=50, verbose_name='Ubicación - Sección')),
                ('ubicacion_repisa', models.CharField(max_length=50, verbose_name='Ubicación - Repisa')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Registro')),
                ('materia', models.CharField(max_length=200, verbose_name='Materia')),
                ('editorial', models.CharField(max_length=200, verbose_name='Editorial')),
                ('edicion', models.CharField(max_length=100, verbose_name='Edición')),
                ('codigo_seccion_full', models.CharField(max_length=100, verbose_name='Código Completo de Sección')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Libro',
                'verbose_name_plural': 'historical Libros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrabajoGrado',
            fields=[
                ('activobibliografico_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='inventario.activobibliografico')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_nuevo', models.CharField(db_index=True, max_length=50, verbose_name='Código Nuevo')),
                ('codigo_antiguo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Antiguo')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autor', models.CharField(max_length=300, verbose_name='Autor')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ubicacion_seccion', models.CharField(max_length=50, verbose_name='Ubicación - Sección')),
                ('ubicacion_repisa', models.CharField(max_length=50, verbose_name='Ubicación - Repisa')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Registro')),
                ('modalidad', models.CharField(choices=[('TESIS', 'Tesis'), ('PROYECTO DE GRADO', 'Proyecto de Grado'), ('TRABAJO DIRIGIDO', 'Trabajo Dirigido')], max_length=30, verbose_name='Modalidad')),
                ('tutor', models.CharField(max_length=300, verbose_name='Tutor')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('facultad', models.CharField(max_length=200, verbose_name='Facultad')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Trabajo de Grado',
                'verbose_name_plural': 'historical Trabajos de Grado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
