# Generated by Django 5.2.8 on 2025-11-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_activobibliografico_codigo_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobibliografico',
            name='codigo_nuevo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código Nuevo'),
        ),
    ]
