# Generated by Django 5.2.8 on 2025-11-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_historicalactivobibliografico_historicallibro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobibliografico',
            name='autor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='activobibliografico',
            name='estado',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activobibliografico',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='activobibliografico',
            name='ubicacion_repisa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Repisa'),
        ),
        migrations.AlterField(
            model_name='activobibliografico',
            name='ubicacion_seccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Sección'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='autor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='estado',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='ubicacion_repisa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Repisa'),
        ),
        migrations.AlterField(
            model_name='historicalactivobibliografico',
            name='ubicacion_seccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Sección'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='autor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='codigo_seccion_full',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Completo de Sección'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='editorial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='estado',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='materia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='ubicacion_repisa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Repisa'),
        ),
        migrations.AlterField(
            model_name='historicallibro',
            name='ubicacion_seccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Sección'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='autor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='carrera',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='estado',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN REPARACION', 'En Reparación')], default='BUENO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='facultad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('TESIS', 'Tesis'), ('PROYECTO DE GRADO', 'Proyecto de Grado'), ('TRABAJO DIRIGIDO', 'Trabajo Dirigido')], max_length=30, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='tutor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='ubicacion_repisa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Repisa'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='ubicacion_seccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación - Sección'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigo_seccion_full',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Completo de Sección'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='materia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='trabajogrado',
            name='carrera',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='trabajogrado',
            name='facultad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='trabajogrado',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('TESIS', 'Tesis'), ('PROYECTO DE GRADO', 'Proyecto de Grado'), ('TRABAJO DIRIGIDO', 'Trabajo Dirigido')], max_length=30, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='trabajogrado',
            name='tutor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tutor'),
        ),
    ]
