# Generated by Django 5.2.8 on 2025-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_activobibliografico_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajogrado',
            name='facultad',
        ),
        migrations.AddField(
            model_name='activobibliografico',
            name='facultad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='historicalactivobibliografico',
            name='facultad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='historicallibro',
            name='facultad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajogrado',
            name='facultad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facultad'),
        ),
    ]
