# Generated by Django 5.2.8 on 2025-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_activobibliografico_codigo_nuevo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['orden_importacion'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='historicallibro',
            name='orden_importacion',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Orden de Importación'),
        ),
        migrations.AddField(
            model_name='libro',
            name='orden_importacion',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Orden de Importación'),
        ),
    ]
