# Generated by Django 5.2.8 on 2025-12-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_libro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('carnet_universitario', models.CharField(max_length=50, unique=True, verbose_name='Carnet Universitario')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALA', 'En Sala (Deja Carnet Universitario)'), ('DOMICILIO', 'A Domicilio (Deja CI - Máximo 2 días)')], max_length=20, verbose_name='Tipo de Préstamo')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_estimada', models.DateTimeField(verbose_name='Fecha de Devolución Estimada')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('DEVUELTO', 'Devuelto'), ('ATRASADO', 'Atrasado')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.activobibliografico', verbose_name='Activo Bibliográfico')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.estudiante', verbose_name='Estudiante')),
                ('usuario_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
